import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';
import Menu from '@/components/Menu';

import {ApolloProviders} from "@/app/ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className="min-h-screen flex flex-col">
            <Header />
            <Menu />
            <div className="flex-grow p-4">{children}</div>
            </body>
        </html>
    );
}
